name = "Anomaly"
uuid = "a40cd781-f393-47f2-8775-4fd2cd5a603c"
authors = ["Marcin Koculak <koculak.marcin@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
